### ISSUE TITLE
[BUG] "Enforcement" of the playground not works?

### ISSUE THREAD

**Issue by fy0** [Permify/permify#1069]
**Describe the bug**
Conflict assertions is both allowed in enforcement.

**To Reproduce**

Empty case with the following code:

![image](https://github.com/Permify/permify/assets/1579850/bf3472e9-5b39-4895-aec9-23a658ab76c0)

```
- name: test
  checks:
    - entity: project:1
      subject: user:1
      assertions:
        read: true
        read: false
```

**Example Application**
https://play.permify.co/?s=gc2RPvd3v1w0Pavdqysm3

**Expected behavior**
One allowed, one rejected.

**Additional context**
-

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: [e.g. macOS]
