### ISSUE TITLE
Pass custom config file in a docker compose file

### ISSUE THREAD

**Issue by mohanyadav** [Permify/permify#1183]
I am creating a docker-compose.yml file and adding some services along with permify. I haven't found a way to include the custom config file in the docker compose. Can someone point me in the right direction?

docker-compose.yml example:
```
version: '3.8'
services:
  permify:
      image: permify/permify:latest
      command: serve
      container_name: permify
      restart: unless-stopped
      ports:
        - "3476:3476"
        - "3478:3478"
      volumes:
        - permify_data:/data/permify
      profiles:
        - dev
        - permify
      
volumes:
  permify_data:
```

**Comment by ioneyed** [comment]
You should be able to pass it in the volumes section

```
version: '3.8'
services:
  permify:
      image: permify/permify:latest
      command: serve
      container_name: permify
      restart: unless-stopped
      ports:
        - "3476:3476"
        - "3478:3478"
      volumes:
        - permify_data:/data/permify
        - /path/to/config/folder:/config
      profiles:
        - dev
        - permify
      
volumes:
  permify_data:
```

Permify looks for the config (in its container) at the root `/config`. It should be a directory with the configuration file or you could add the config file to your `permify_data` volume and make the command `serve -c /permify_data/config.yaml`

The final option, would be using cli flags to configure the settings in the `command` of the compose.

**Comment by junwen-k** [comment]
Another option is to use [environment variables](https://docs.permify.co/setting-up/configuration) to configure your permify server. In my opinion this is cleaner and easier. E.g,

`docker-compose.yml`
```yaml
...

services:
  postgres:
    ...

  permify:
    ...
    # https://docs.permify.co/setting-up/configuration
    environment:
      PERMIFY_DATABASE_ENGINE: postgres
      # `postgres` is referring to postgres `postgres` docker container.
      PERMIFY_DATABASE_URI: postgresql://user:password@postgres/postgres
      PERMIFY_DATABASE_GARBAGE_COLLECTION_ENABLED: true
    ...

...
```
