### ISSUE TITLE
[BUG] Permify on AWS EKS using an RDS PostgreSQL

### ISSUE THREAD

**Issue by fagihms** [Permify/permify#1340]
**Describe the bug**
Hello!
I'm trying to use Permify on AWS EKS using an RDS PostgreSQL instance as database.
When the pod try to start, it crashed after a while with the error message:
```
msg="failed to initialize database"
error="pinging pools failed: write pool ping failed: failed to connect to ... server error: FATAL: Feature not supported: RDS Proxy currently doesn’t support the option plan_cache_mode. (SQLSTATE 0A000)"
```

**To Reproduce**
I applied the deployment using kubectl with the following configuration
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: permify
  name: permify
spec:
  selector:
    matchLabels:
      app: permify
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: permify
    spec:
      serviceAccountName: aws-access-service-account
      restartPolicy: Always
      containers:
        - env:
            - name: PERMIFY_DATABASE_ENGINE
              value: postgres
            - name: PERMIFY_DATABASE_URI
              value: postgresql://$(DATASOURCE_USERNAME):$(DATASOURCE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(ENV_NAME)_permify
            - name: PERMIFY_DATABASE_MAX_OPEN_CONNECTIONS
              value: "20"
            - name: PERMIFY_LOG_LEVEL
              value: "trace"
            - name: PERMIFY_DATABASE_AUTO_MIGRATE
              value: "false"
          image: ghcr.io/permify/permify
          name: permify
          args:
            - "serve"
          ports:
            - containerPort: 3476
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
```

**Expected behavior**
I expected that Permify can connect to my PostgreSQL database and initialize its tables.

**Environment (please complete the following information, because it helps us investigate better):**
 - PostgreSQL version: Aurora PostgreSQL (Compatible with PostgreSQL 15.4) - default for major version 15
 - Permify version: v0.9.8
