### ISSUE TITLE
[BUG] Garbage Collector removing relation still valid

### ISSUE THREAD

**Issue by gign0766** [Permify/permify#1471]
**Describe the bug**
When a permission is present twice, one valid and the other expired, the Garbage Collector invalidate the relation in spite of relation their is still valid one

**To Reproduce**

Setup a Permify with a PostgreSQL database, configure the garbage collector as following : 
```yml
database:
  engine: postgres
  uri: 
  garbage_collection:
     enabled: true
     interval: 10m
     window: 5m
     timeout: 5m
```

Add a relation, then add the same relation (for the same tenant) a bit later

For example : 
![image](https://github.com/user-attachments/assets/87c87f6f-26c7-48b2-bce0-04a632cbd4e7)

The permission check work until the garbage collector run, after that, the permission is considered as invalid

**Expected behavior**
The expired relation should be removed from the database, but the permission check should still be allowed since there is a valid relation.

**Additional context**
The permify instance run with the helm chart as well as the postgres instance

**Environment :**
 - Permify : helmchart permify v0.3.5
 - Postgres : bitnami postgresql 12.5
