### ISSUE TITLE
Undocumented Configuration Parameter: `backoff_frequency`

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#1529]
#### Description
It appears that there is an undocumented configuration parameter `backoff_frequency` under the OIDC configuration. While the configuration itself is functional, it is not mentioned in the documentation, leading to confusion for users trying to configure their OIDC setup.

#### Configuration Example:
```yaml
oidc:
    issuer: <issuer>
    audience: <audience>
    refresh_interval: 5m
    backoff_interval: 1m
    backoff_frequency: 5s
    backoff_max_retries: 5
    valid_methods: ['RS256', 'HS256']
```

#### Configure the OIDC settings as shown in the example.

Notice that the backoff_frequency parameter, although required, is not documented.

#### Expected Behavior

The backoff_frequency parameter should be documented along with its default value and potential usage scenarios.

#### Actual Behavior

The backoff_frequency parameter is not mentioned in the current documentation, which may cause confusion among users.
