### ISSUE TITLE
Develop Simplified Assertion Definitions and Reduced Duplication for Permify Validate Action

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#422]
**Objective:**

Create a test framework that builds upon the existing permify-validate functionality to better handle multiple permutations, simplify assertion definitions, and minimize duplication.

**Tasks:**

1. Design a more structured approach for defining assertions, allowing multiple checks per entity and subject:

```yaml
assertions:
  - entity: "user:1"
    checks:
      - "view" : true
      - "edit" : false
    subject: "thing:1"
```

2. Add support for multiple entities and subjects in a single entry:

```yaml
assertions:
  - entity: ["user:1", "user:2"]
    checks:
      - "view" : true
      - "edit" : false
    subject: ["thing:1", "thing:2"]
```

- Update the permify-validate function to accommodate the new structured approach.
- Write tests to confirm the functionality and robustness of the new test framework features.
- Update documentation to reflect the changes, providing usage examples for the new approach.
- Submit a pull request for review and address any feedback from the team.

Implementing these features will greatly simplify the process of defining complex authorization policies and reduce the burden of duplicating statements, leading to a more efficient and enjoyable experience for our users.
