### ISSUE TITLE
[BUG] Permission check success when no relationship is present.

### ISSUE THREAD

**Issue by slimdevl** [Permify/permify#730]
**Describe the bug**
Using a the failure-scenario-schema.yml below, and the current docker - permission checks pass when no relationships are present.

Did I misconfigure the schema? Why would these checks pass with zero relationships?

**failure-scenario-schema**
```yaml
schema: >-
  entity user {}

  entity organization {
      relation admin @user
      relation member @user
  }

  entity team {
      // Access Control Group
      // Is a group of users within an single organization
      // which have a shared permission level with a project

      // The organization the team members belongs to
      relation org @organization
      
      // The owner (point of contact) of the group - who is part of org
      relation owner @user

      // direct members of the group
      relation member @user

      // Allows a group member to leave - self manage membership
      permission leave = member

      // Permissions that can be performed only by:
      // 1. The owner in the same organization or
      // 2. The admin of the same organization
      // NOTE: This allows the org to manage it's own memberships in this group
      permission edit         = (org.member and (org.admin or owner))
      permission delete       = (org.member and (org.admin or owner))
      permission invite       = (org.member and (org.admin or owner))
      permission remove_user  = (org.member and (org.admin or owner))
      permission change_owner = (org.member and org.admin)
  }

  entity project {
      // represents parent organization and owner which own the project
      relation org @organization
      relation owner @user

      // The following are various levels of permissions/access
      // 1. Each represents a set of one or more user groups (see team above)
      // 2. Each ac_group in a specific category is members from a specific org with permissions for that level
      //    a. This allows the org group to manage it's own member
      relation admin @team
      relation editor @team
      relation collaborator @team
      relation commenter @team
      relation viewer @team

      // hard permissions/actions based on roles (team level above)
      permission leave          = viewer.owner or editor.owner or collaborator.owner or commenter.owner or admin.owner
      permission view           = owner or org.admin or viewer.member or commenter.member or collaborator.member or editor.member or admin.member
      permission comment        = owner or commenter.member or collaborator.member or editor.member or admin.member
      permission edit_add       = owner or collaborator.member or editor.member or admin.member
      // these are permission restricted to only owners/admins of the group
      // they must be part of the organization to perform these duties
      permission edit_perms     = (org.member and (owner or org.admin or admin.member))
      permission edit_delete    = (org.member and (owner or org.admin or admin.member or editor.member))
      permission invite_team  = (org.member and (org.admin or owner or admin.member))
      permission remove_team  = (org.member and (org.admin or owner or admin.member))
      permission delete         = (org.member and (org.admin or owner))
  }  

# no relationships (test we can make sure all tests fail first)
relationships:

scenarios:
  - name: "Organization 1 project"
    checks:
      - entity: "project:1"
        subject: "user:1"
        assertions:
          view: true
          leave: true
          comment: true
          edit_add: true
          edit_delete: true
          edit_perms: true
          invite_team: true
          remove_team: true
          delete: true
      - entity: "project:1"
        subject: "user:2"     # member/admin
        assertions:
          view: true
          leave: false
          comment: true
          edit_add: true
          edit_delete: true
          edit_perms: true
          invite_team: true
          remove_team: true
          delete: false
      - entity: "project:1"
        subject: "user:7"     #  Dev team Collaborator
        assertions:
          view: true
          leave: false
          comment: true
          edit_add: true
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:1"
        subject: "user:16"     # Contractor 1 
        assertions:
          view: true
          leave: false
          comment: true
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:1"
        subject: "user:17"     # Contractor 2 
        assertions:
          view: true
          leave: true          # can leave because team admin
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
  - name: "Organization 2 Dev team 1 project"
    checks:
      - entity: "project:2"
        subject: "user:1"     # organization boss has no permissions
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:2"
        subject: "user:10"     # member/admin (sec team)
        assertions:
          view: true
          leave: true
          comment: true
          edit_add: true
          edit_delete: true
          edit_perms: true
          invite_team: true
          remove_team: true
          delete: true
      - entity: "project:2"
        subject: "user:7"     # member/admin (dev team)
        assertions:
          view: true
          leave: false
          comment: true
          edit_add: true
          edit_delete: true
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:2"
        subject: "user:12"     # Pointy Haired Bob has no power
        assertions:
          view: true
          leave: true          # Yep - he owns team 5 (leave commenter team)
          comment: true
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
  - name: "Organization 2 Dev team 2 project"
    checks:
      - entity: "project:3"
        subject: "user:6"     # org.admin (not on team)
        assertions:
          view: true
          leave: false
          comment: false
          edit_add: false
          edit_delete: true  # these are true because org.admin
          edit_perms: true
          invite_team: true
          remove_team: true
          delete: true
      - entity: "project:3"
        subject: "user:7"     # Dev team 1 no permissions
        assertions:
          view: false
          leave: false        
          comment: false
          edit_add: false
          edit_delete: false 
          edit_perms: false  
          invite_team: false 
          remove_team: false
          delete: false
      - entity: "project:3"
        subject: "user:10"     # member/admin (sec team)
        assertions:
          view: true
          leave: true         # owner, and admin
          comment: true
          edit_add: true
          edit_delete: true
          edit_perms: true
          invite_team: true
          remove_team: true
          delete: true
      - entity: "project:3"
        subject: "user:8"     # member/admin (dev team)
        assertions:
          view: true
          leave: true
          comment: true
          edit_add: true
          edit_delete: true
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:3"
        subject: "user:9"     # member/admin (dev team)
        assertions:
          view: true
          leave: false
          comment: true
          edit_add: true
          edit_delete: true
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
```

**To Reproduce**
```
docker run -it -v ${PWD}/failure-scenario-schema.yml:/schema.yml:ro ghcr.io/permify/permify validate /schema.yml
```

**Additional context**
First let me start with - this project is AWESOME! Thank you for this. Much cleaner that FGA DSL. 

Secondly, I am new to the project, so I am not sure if my schema is misconfigured - but I followed all the examples. Maybe I misunderstand permission definition?

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: linux
 - Version Ubuntu 22.04

**Comment by tolgaOzen** [comment]
Hello @slimdevl ,

We've tested the model you sent over, and the assertions didn't result in a pass as you face. Here are the results we got:

Playground
https://play.permify.co/?s=fitpJtmkzE2_Lw0SVnYbX&tab=enforcement

For Docker, we ran:

```
 docker run -it -v ${PWD}/config/validation.yaml:/schema.yml:ro ghcr.io/permify/permify validate /schema.yml
```

<img width="596" alt="Screenshot 2023-10-01 at 8 05 34 PM" src="https://github.com/Permify/permify/assets/39353278/ce1d7ee6-12ec-4030-ad39-a7f5fca0455b">

It shouldn't' have shown a pass. Do you have a screenshot of your results when running this? Can you share it with us?

**Comment by slimdevl** [comment]
I received something very similar. Most all checks `fail` - which was the expected result. The `success` cases you share is what gave me concern. 

Notice there are a number of `success` results in the test scenarios - which I thought should have been `failed` for every one. Am I mistaken?

![Screenshot 2023-10-01 at 2 35 58 PM](https://github.com/Permify/permify/assets/74689600/486f775e-7015-43f4-b3da-3b58a96a7ca6)

Here is the full output of my run. 
```
docker run -it -v ${PWD}/failure-scenario.yml:/schema.yml:ro ghcr.io/permify/permify validate /schema.yml
schema is creating... 🚀
  success
relationships are creating... 🚀
attributes are creating... 🚀
checking scenarios... 🚀
1.scenario: Organization 1 project - 
  checks:
    fail: user:1 invite_team project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 comment project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 edit_perms project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 edit_add project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 edit_delete project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 remove_team project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 delete project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 view project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:1 leave project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:2 delete project:1 
    fail: user:2 view project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:2 leave project:1 
    fail: user:2 comment project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:2 edit_add project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:2 edit_delete project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:2 remove_team project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:2 edit_perms project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:2 invite_team project:1 ->  expected: ALLOWED actual: DENIED 
    fail: user:7 edit_add project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:7 edit_perms project:1 
    success: user:7 invite_team project:1 
    success: user:7 delete project:1 
    fail: user:7 view project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:7 leave project:1 
    fail: user:7 comment project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:7 edit_delete project:1 
    success: user:7 remove_team project:1 
    fail: user:16 view project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:16 edit_add project:1 
    success: user:16 remove_team project:1 
    success: user:16 leave project:1 
    fail: user:16 comment project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:16 edit_delete project:1 
    success: user:16 edit_perms project:1 
    success: user:16 invite_team project:1 
    success: user:16 delete project:1 
    fail: user:17 leave project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:17 edit_add project:1 
    fail: user:17 view project:1 ->  expected: ALLOWED actual: DENIED 
    success: user:17 edit_delete project:1 
    success: user:17 edit_perms project:1 
    success: user:17 invite_team project:1 
    success: user:17 remove_team project:1 
    success: user:17 delete project:1 
    success: user:17 comment project:1 
  entity_filters:
  subject_filters:
2.scenario: Organization 2 Dev team 1 project - 
  checks:
    success: user:1 view project:2 
    success: user:1 edit_add project:2 
    success: user:1 edit_perms project:2 
    success: user:1 leave project:2 
    success: user:1 comment project:2 
    success: user:1 edit_delete project:2 
    success: user:1 invite_team project:2 
    success: user:1 remove_team project:2 
    success: user:1 delete project:2 
    fail: user:10 edit_add project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 edit_delete project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 invite_team project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 delete project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 comment project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 leave project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 edit_perms project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 remove_team project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 view project:2 ->  expected: ALLOWED actual: DENIED 
    success: user:7 leave project:2 
    fail: user:7 edit_delete project:2 ->  expected: ALLOWED actual: DENIED 
    success: user:7 edit_perms project:2 
    success: user:7 delete project:2 
    fail: user:7 view project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:7 comment project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:7 edit_add project:2 ->  expected: ALLOWED actual: DENIED 
    success: user:7 invite_team project:2 
    success: user:7 remove_team project:2 
    fail: user:12 comment project:2 ->  expected: ALLOWED actual: DENIED 
    success: user:12 invite_team project:2 
    success: user:12 remove_team project:2 
    fail: user:12 view project:2 ->  expected: ALLOWED actual: DENIED 
    fail: user:12 leave project:2 ->  expected: ALLOWED actual: DENIED 
    success: user:12 edit_perms project:2 
    success: user:12 delete project:2 
    success: user:12 edit_add project:2 
    success: user:12 edit_delete project:2 
  entity_filters:
  subject_filters:
3.scenario: Organization 2 Dev team 2 project - 
  checks:
    fail: user:6 view project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:6 leave project:3 
    success: user:6 comment project:3 
    fail: user:6 edit_delete project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:6 remove_team project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:6 edit_add project:3 
    fail: user:6 edit_perms project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:6 invite_team project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:6 delete project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:7 invite_team project:3 
    success: user:7 leave project:3 
    success: user:7 comment project:3 
    success: user:7 edit_delete project:3 
    success: user:7 edit_perms project:3 
    success: user:7 remove_team project:3 
    success: user:7 delete project:3 
    success: user:7 view project:3 
    success: user:7 edit_add project:3 
    fail: user:10 leave project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 comment project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 edit_delete project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 invite_team project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 delete project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 view project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 edit_add project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 edit_perms project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:10 remove_team project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:8 edit_delete project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:8 remove_team project:3 
    fail: user:8 view project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:8 leave project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:8 edit_perms project:3 
    success: user:8 invite_team project:3 
    success: user:8 delete project:3 
    fail: user:8 comment project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:8 edit_add project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:9 comment project:3 ->  expected: ALLOWED actual: DENIED 
    fail: user:9 edit_delete project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:9 invite_team project:3 
    success: user:9 remove_team project:3 
    success: user:9 delete project:3 
    fail: user:9 view project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:9 leave project:3 
    fail: user:9 edit_add project:3 ->  expected: ALLOWED actual: DENIED 
    success: user:9 edit_perms project:3 
  entity_filters:
  subject_filters:
fails:
fail: user:1 invite team project:1 -> expected: allowed actual: denied 
fail: user:1 comment project:1 -> expected: allowed actual: denied 
fail: user:1 edit perms project:1 -> expected: allowed actual: denied 
fail: user:1 edit add project:1 -> expected: allowed actual: denied 
fail: user:1 edit delete project:1 -> expected: allowed actual: denied 
fail: user:1 remove team project:1 -> expected: allowed actual: denied 
fail: user:1 delete project:1 -> expected: allowed actual: denied 
fail: user:1 view project:1 -> expected: allowed actual: denied 
fail: user:1 leave project:1 -> expected: allowed actual: denied 
fail: user:2 view project:1 -> expected: allowed actual: denied 
fail: user:2 comment project:1 -> expected: allowed actual: denied 
fail: user:2 edit add project:1 -> expected: allowed actual: denied 
fail: user:2 edit delete project:1 -> expected: allowed actual: denied 
fail: user:2 remove team project:1 -> expected: allowed actual: denied 
fail: user:2 edit perms project:1 -> expected: allowed actual: denied 
fail: user:2 invite team project:1 -> expected: allowed actual: denied 
fail: user:7 edit add project:1 -> expected: allowed actual: denied 
fail: user:7 view project:1 -> expected: allowed actual: denied 
fail: user:7 comment project:1 -> expected: allowed actual: denied 
fail: user:16 view project:1 -> expected: allowed actual: denied 
fail: user:16 comment project:1 -> expected: allowed actual: denied 
fail: user:17 leave project:1 -> expected: allowed actual: denied 
fail: user:17 view project:1 -> expected: allowed actual: denied 
fail: user:10 edit add project:2 -> expected: allowed actual: denied 
fail: user:10 edit delete project:2 -> expected: allowed actual: denied 
fail: user:10 invite team project:2 -> expected: allowed actual: denied 
fail: user:10 delete project:2 -> expected: allowed actual: denied 
fail: user:10 comment project:2 -> expected: allowed actual: denied 
fail: user:10 leave project:2 -> expected: allowed actual: denied 
fail: user:10 edit perms project:2 -> expected: allowed actual: denied 
fail: user:10 remove team project:2 -> expected: allowed actual: denied 
fail: user:10 view project:2 -> expected: allowed actual: denied 
fail: user:7 edit delete project:2 -> expected: allowed actual: denied 
fail: user:7 view project:2 -> expected: allowed actual: denied 
fail: user:7 comment project:2 -> expected: allowed actual: denied 
fail: user:7 edit add project:2 -> expected: allowed actual: denied 
fail: user:12 comment project:2 -> expected: allowed actual: denied 
fail: user:12 view project:2 -> expected: allowed actual: denied 
fail: user:12 leave project:2 -> expected: allowed actual: denied 
fail: user:6 view project:3 -> expected: allowed actual: denied 
fail: user:6 edit delete project:3 -> expected: allowed actual: denied 
fail: user:6 remove team project:3 -> expected: allowed actual: denied 
fail: user:6 edit perms project:3 -> expected: allowed actual: denied 
fail: user:6 invite team project:3 -> expected: allowed actual: denied 
fail: user:6 delete project:3 -> expected: allowed actual: denied 
fail: user:10 leave project:3 -> expected: allowed actual: denied 
fail: user:10 comment project:3 -> expected: allowed actual: denied 
fail: user:10 edit delete project:3 -> expected: allowed actual: denied 
fail: user:10 invite team project:3 -> expected: allowed actual: denied 
fail: user:10 delete project:3 -> expected: allowed actual: denied 
fail: user:10 view project:3 -> expected: allowed actual: denied 
fail: user:10 edit add project:3 -> expected: allowed actual: denied 
fail: user:10 edit perms project:3 -> expected: allowed actual: denied 
fail: user:10 remove team project:3 -> expected: allowed actual: denied 
fail: user:8 edit delete project:3 -> expected: allowed actual: denied 
fail: user:8 view project:3 -> expected: allowed actual: denied 
fail: user:8 leave project:3 -> expected: allowed actual: denied 
fail: user:8 comment project:3 -> expected: allowed actual: denied 
fail: user:8 edit add project:3 -> expected: allowed actual: denied 
fail: user:9 comment project:3 -> expected: allowed actual: denied 
fail: user:9 edit delete project:3 -> expected: allowed actual: denied 
fail: user:9 view project:3 -> expected: allowed actual: denied 
fail: user:9 edit add project:3 -> expected: allowed actual: denied 
FAILED
```

**Comment by slimdevl** [comment]
One more data point (docker images):
```
ghcr.io/permify/permify                                               latest                           9779f7822e11   13 days ago     42.2MB
```

**Comment by tolgaOzen** [comment]
Yes @slimdevl , the reason for that is because those assertions are set to 'false'. Since they are set to false, they pass. If you mark all assertions as false, all validations will return as success.

**Comment by tolgaOzen** [comment]
Even if there’s no relation, the assertions you’ve marked as ‘false’ are actually successful.

**Comment by slimdevl** [comment]
OGM! That makes total sense! I'm sorry for bothering you on Sunday.

This is clearly my mistake.  I have been moving quickly to check this project out and:
1. test 1: add relationships - validate scenarios
2. test 2: remove relationships (comment out) - test scenarios. 

However the scenarios as you point out should all be set to `false`.

Thank you very much for your fast response! I love this project. Can't wait to see the commercial offering ;-)

**Comment by slimdevl** [comment]
Follow up for future readers. The scenarios should be all set to false with no relationships:
```
scenarios:
  - name: "Organization 1 project"
    checks:
      - entity: "project:1"
        subject: "user:1"
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:1"
        subject: "user:2"     # member/admin
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:1"
        subject: "user:7"     #  Dev team Collaborator
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:1"
        subject: "user:16"     # Contractor 1 
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:1"
        subject: "user:17"     # Contractor 2 
        assertions:
          view: false
          leave: false          # can leave because team admin
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
  - name: "Organization 2 Dev team 1 project"
    checks:
      - entity: "project:2"
        subject: "user:1"     # organization boss has no permissions
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:2"
        subject: "user:10"     # member/admin (sec team)
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:2"
        subject: "user:7"     # member/admin (dev team)
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:2"
        subject: "user:12"     # Pointy Haired Bob has no power
        assertions:
          view: false
          leave: false          # Yep - he owns team 5 (leave commenter team)
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
  - name: "Organization 2 Dev team 2 project"
    checks:
      - entity: "project:3"
        subject: "user:6"     # org.admin (not on team)
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false  # these are false because org.admin
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:3"
        subject: "user:7"     # Dev team 1 no permissions
        assertions:
          view: false
          leave: false        
          comment: false
          edit_add: false
          edit_delete: false 
          edit_perms: false  
          invite_team: false 
          remove_team: false
          delete: false
      - entity: "project:3"
        subject: "user:10"     # member/admin (sec team)
        assertions:
          view: false
          leave: false         # owner, and admin
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:3"
        subject: "user:8"     # member/admin (dev team)
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
      - entity: "project:3"
        subject: "user:9"     # member/admin (dev team)
        assertions:
          view: false
          leave: false
          comment: false
          edit_add: false
          edit_delete: false
          edit_perms: false
          invite_team: false
          remove_team: false
          delete: false
```

Expected (and correct output):
```
docker run -it -v ${PWD}/failure-scenario.yml:/schema.yml:ro ghcr.io/permify/permify validate /schema.yml
schema is creating... 🚀
  success
relationships are creating... 🚀
attributes are creating... 🚀
checking scenarios... 🚀
1.scenario: Organization 1 project - 
  checks:
    success: user:1 invite_team project:1 
    success: user:1 view project:1 
    success: user:1 leave project:1 
    success: user:1 comment project:1 
    success: user:1 edit_add project:1 
    success: user:1 edit_delete project:1 
    success: user:1 edit_perms project:1 
    success: user:1 remove_team project:1 
    success: user:1 delete project:1 
    success: user:2 view project:1 
    success: user:2 leave project:1 
    success: user:2 comment project:1 
    success: user:2 edit_delete project:1 
    success: user:2 edit_perms project:1 
    success: user:2 invite_team project:1 
    success: user:2 remove_team project:1 
    success: user:2 edit_add project:1 
    success: user:2 delete project:1 
    success: user:7 remove_team project:1 
    success: user:7 leave project:1 
    success: user:7 comment project:1 
    success: user:7 edit_add project:1 
    success: user:7 invite_team project:1 
    success: user:7 view project:1 
    success: user:7 edit_delete project:1 
    success: user:7 edit_perms project:1 
    success: user:7 delete project:1 
    success: user:16 edit_delete project:1 
    success: user:16 edit_perms project:1 
    success: user:16 remove_team project:1 
    success: user:16 view project:1 
    success: user:16 comment project:1 
    success: user:16 invite_team project:1 
    success: user:16 delete project:1 
    success: user:16 leave project:1 
    success: user:16 edit_add project:1 
    success: user:17 leave project:1 
    success: user:17 edit_delete project:1 
    success: user:17 edit_perms project:1 
    success: user:17 remove_team project:1 
    success: user:17 delete project:1 
    success: user:17 view project:1 
    success: user:17 comment project:1 
    success: user:17 edit_add project:1 
    success: user:17 invite_team project:1 
  entity_filters:
  subject_filters:
2.scenario: Organization 2 Dev team 1 project - 
  checks:
    success: user:1 comment project:2 
    success: user:1 edit_add project:2 
    success: user:1 delete project:2 
    success: user:1 view project:2 
    success: user:1 leave project:2 
    success: user:1 edit_delete project:2 
    success: user:1 edit_perms project:2 
    success: user:1 invite_team project:2 
    success: user:1 remove_team project:2 
    success: user:10 comment project:2 
    success: user:10 remove_team project:2 
    success: user:10 edit_perms project:2 
    success: user:10 invite_team project:2 
    success: user:10 delete project:2 
    success: user:10 view project:2 
    success: user:10 leave project:2 
    success: user:10 edit_add project:2 
    success: user:10 edit_delete project:2 
    success: user:7 view project:2 
    success: user:7 leave project:2 
    success: user:7 remove_team project:2 
    success: user:7 comment project:2 
    success: user:7 edit_add project:2 
    success: user:7 edit_delete project:2 
    success: user:7 edit_perms project:2 
    success: user:7 invite_team project:2 
    success: user:7 delete project:2 
    success: user:12 leave project:2 
    success: user:12 edit_delete project:2 
    success: user:12 delete project:2 
    success: user:12 invite_team project:2 
    success: user:12 remove_team project:2 
    success: user:12 view project:2 
    success: user:12 comment project:2 
    success: user:12 edit_add project:2 
    success: user:12 edit_perms project:2 
  entity_filters:
  subject_filters:
3.scenario: Organization 2 Dev team 2 project - 
  checks:
    success: user:6 view project:3 
    success: user:6 comment project:3 
    success: user:6 invite_team project:3 
    success: user:6 leave project:3 
    success: user:6 edit_add project:3 
    success: user:6 edit_delete project:3 
    success: user:6 edit_perms project:3 
    success: user:6 remove_team project:3 
    success: user:6 delete project:3 
    success: user:7 view project:3 
    success: user:7 comment project:3 
    success: user:7 edit_add project:3 
    success: user:7 edit_delete project:3 
    success: user:7 remove_team project:3 
    success: user:7 leave project:3 
    success: user:7 edit_perms project:3 
    success: user:7 invite_team project:3 
    success: user:7 delete project:3 
    success: user:10 edit_perms project:3 
    success: user:10 invite_team project:3 
    success: user:10 delete project:3 
    success: user:10 view project:3 
    success: user:10 comment project:3 
    success: user:10 edit_add project:3 
    success: user:10 leave project:3 
    success: user:10 edit_delete project:3 
    success: user:10 remove_team project:3 
    success: user:8 leave project:3 
    success: user:8 remove_team project:3 
    success: user:8 view project:3 
    success: user:8 comment project:3 
    success: user:8 edit_add project:3 
    success: user:8 edit_delete project:3 
    success: user:8 edit_perms project:3 
    success: user:8 invite_team project:3 
    success: user:8 delete project:3 
    success: user:9 edit_add project:3 
    success: user:9 edit_perms project:3 
    success: user:9 invite_team project:3 
    success: user:9 remove_team project:3 
    success: user:9 delete project:3 
    success: user:9 view project:3 
    success: user:9 leave project:3 
    success: user:9 comment project:3 
    success: user:9 edit_delete project:3 
  entity_filters:
  subject_filters:
schema successfully created
relationships successfully created
assertions successfully passed
SUCCESS
```
