### ISSUE TITLE
Flexible Input Formats for Schema in Testing Validation File

### ISSUE THREAD

**Issue by tolgaOzen** [Permify/permify#840]
We are seeking to expand the capabilities of our testing validation file structure. Our current schema configuration is structured as follows:

```yaml
schema: |-
    entity user {}
    entity role {
        relation assignee @user
    }

relationships:
    - dashboard:project-progress#view@role:admin#assignee

attributes:

scenarios:
    - name: "User Dashboard View Permissions"
      // ... scenario details ...
    // ... other scenarios ...
```

### Proposed Enhancement

**Enhancement Overview:** I propose we expand the schema field to accept input as a simple string text representing either a URL or a file path, in addition to the current direct string input.

**Objective:** This enhancement is intended to increase flexibility in how we input and manage schema data, allowing us to adapt to various testing requirements more effectively.

New Input Options with Format Specifications

**1. URL Input (String Text):**
```yaml
schema: "http://example.com/schema/user-role-schema"
```
For URL input, the system should be capable of fetching the schema as a plain text file from the specified URL.

2. File Path Input (String Text):
```yaml
schema: "/path/to/local/schema-file.txt"
```
Here, the input is a simple string representing the file path, and the system should read the schema as a plain text file from this location.

3. Direct String Input (Current Method):
```yaml
schema: |-
    entity user {}
    entity role {
        relation assignee @user
    }
```
This method remains unchanged, where the schema is input directly as a YAML formatted string.

**Benefits**

**Enhanced Flexibility:** Supports different methods of inputting schema data.
**Streamlined Testing:** Facilitates easier switching between schemas, enhancing testing efficiency.
**User-Friendly:** Provides multiple intuitive options for defining schemas.
